### ISSUE TITLE
Add support for nested routes.

### ISSUE THREAD

**Issue by raniesantos** [raniesantos/vue-routisan#25]

**Comment by blogui91** [comment]
Hello @raniesantos  Nice package and nice work! I will implement it in some projects I have.
 Well, about this feature I would like to know if this feature will come soon. Anyway, I will subscribe to this thread for additional updates! Waiting for this feature, Thank you!

**Comment by raniesantos** [comment]
@blogui91 https://github.com/raniesantos/vue-routisan#nested-routes
