### ISSUE TITLE
Routing not working correctly when using :param as prefix

### ISSUE THREAD

**Issue by blogui91** [raniesantos/vue-routisan#32]
Hello I am having some difficulties with this scenario

I have the following routes
![image](https://user-images.githubusercontent.com/5723380/37861386-2d00561a-2efe-11e8-81d5-630990573d68.png)

For example, if I am in a children view and use router.push({ name: 'app.car_details' , params: { dealership: 'somename' }} to move next, the route is not appending the param *dealership* 
![image](https://user-images.githubusercontent.com/5723380/37861433-2e0cde24-2eff-11e8-8c89-90ad28f7c54b.png)

I should see http://site.app/somename/details
instead of  http://site.app/details

However, If I declare the routes like this, It will work fine
![image](https://user-images.githubusercontent.com/5723380/37861451-815f98a0-2eff-11e8-8238-facf1a1c2815.png)

is this a correct behavior?

Thanks in advance!

**Comment by raniesantos** [comment]
@blogui91 I haven't actually used nested+child routes in Vue a lot, so I have to ask, will the first set of routes work (assuming you change it back to default Vue syntax) without problems?

**Comment by raniesantos** [comment]
You could also greatly help me debug this by showing me the output of this when you add it to your code:

```js
Route.all().forEach(r => console.log(r.path));
```

**Comment by blogui91** [comment]
https://kopy.io/RRVgQ These are my routes
And the log is 
![image](https://user-images.githubusercontent.com/5723380/37862023-102868da-2f0c-11e8-9a22-015671141e61.png)
Anyway, let me switch the routes to v-router syntax as you mention above to see if it works

**Comment by raniesantos** [comment]
Related: https://forum.vuejs.org/t/params-dynamic-nested-routes-vue/14749

**Comment by blogui91** [comment]
Cool! Thanks for your support @raniesantos  It worked, i am closing the issue

**Comment by raniesantos** [comment]
@blogui91 So what was the problem? You were using the dynamic route parameter incorrectly?

**Comment by blogui91** [comment]
@raniesantos sorry for the ong delay, i just added a prop _dealership_ in my layout.
