### ISSUE TITLE
Rendering comented function?

### ISSUE THREAD

**Issue by diego-lipinski-de-castro** [raniesantos/vue-routisan#33]
Problem: when I use vue-routisan, the vue-router actually returns a comment in the html (like the image in the end) , when I use the vue-router alone, without vue-routisan, it works as expected

"vue": "^2.5.2",
"vue-router": "^3.0.1",
"vue-routisan": "^2.1.0",
"vuex": "^3.0.1",
"vuex-router-sync": "^5.0.0"

index.js

```javascript
import Vue from 'vue'
import Router from 'vue-router'
import routes from './routes'

Vue.use(Router)

const router = new Router({
    mode: 'hash',
    linkActiveClass: 'router-link-active',
    linkExactActiveClass: 'router-link-exact-active',
    scrollBehavior: () => { y: 0 },
    routes: routes
})

export default router

```

routes.js

```javascript
import Routes from 'vue-routisan'

Routes.setViewResolver((path) => import(`./../${path}`))
// I also tried the readme way, which is Routes.setViewResolver((path) => require('./../' + path))

Routes.view('/', 'pages/home')

export default Routes.all()

```
result
![screenshot_2018-04-14 13 31 16_7sodj7](https://user-images.githubusercontent.com/29608698/38770356-42752412-3fe8-11e8-8fda-46be4d8079a9.png)

**Comment by raniesantos** [comment]
Can you do these to help me better understand the problem:

1. Only include the necessary code (if its commented-out don't paste it in)
2. Give me at least 1 to 2 sentences of explaining the issue.

**Comment by diego-lipinski-de-castro** [comment]
I updated the issue

**Comment by raniesantos** [comment]
Is this a private project or can I clone your code on GitHub?

Note: I can't actually work on this right now so please be patient.

**Comment by raniesantos** [comment]
Here's something you can try for now. If you console.log `Routes.all()` and look carefully at each element of the routes array, do they look okay?

Are the paths formatted properly?

**Comment by raniesantos** [comment]
Note: dealing with "life stuff", can't find the time to squeeze this in at the moment. Just in case you're wondering what's taking so long.

**Comment by diego-lipinski-de-castro** [comment]
No problem, I can stand with vue-router alone while having this issue (btw I still got no idea why thats happening). Also, good luck boi ;)

**Comment by raniesantos** [comment]
Ok so this solves it for the webpack dynamic import.

`Routes.setViewResolver((path) => () => import(`./../${path}`))`

I'm not entirely sure why the require statement doesn't work though.

Is the require method disabled in your webpack config?

**Comment by raniesantos** [comment]
I'll leave this open if you don't mind, until I find the reason why require('path/to/component') isn't working.

**Comment by diego-lipinski-de-castro** [comment]
Fine by me, you could open over there to if needed, I dont update my projects daily but its fine by me

**Comment by raniesantos** [comment]
Just unsubscribe to this thread because I might post some self-notes here. I don't want to flood you with notifications.

**Comment by diego-lipinski-de-castro** [comment]
Ok, gl
