### ISSUE TITLE
 turning off setViewResolver , this would not work with SSR

### ISSUE THREAD

**Issue by codeitlikemiley** [raniesantos/vue-routisan#37]
```js
//src/routes/index.js
import home from '~/routes/home'

let routeFiles = []
/* Multi Route Files */
const routes = routeFiles.concat(
  home
  /* add here Other Routes File */
)
export default routes
```

```js
//src/routes/home/index.js
import Route from 'vue-routisan'
Route.setViewResolver(c => require('~/pages/' + c).default)
Route.view('/', 'index')
export default Route.all()
```
This produce an error `render function or template not defined in component: anonymous`

There should be a way not to use dynamic import thus turning off the resolver, this would work on nuxt on SPA but on SSR mode this wouldnt. Since with SSR The Routes Needs to be define With each pages component, Since it will be serve depending on users url.

Either Do it like this, and make resolver turn off by default...

```js
//src/routes/home/index.js
import Route from 'vue-routisan'
import Home from '~/pages/index.vue'
Route.view('/', Home)
export default Route.all()
```

**Comment by codeitlikemiley** [comment]
other way is to make 2nd params nullable for the component , and just passed the component in components options like so

```
Route.view('/').options({
  name: 'home',
  components: Home
})
const routes = Route.all()
```

if we check the official docs of vue router 
they have this options
```
components?: { [name: string]: Component }; // for named views
```

**Comment by codeitlikemiley** [comment]
what will happen if u dont pass a resolver? what would be the default value?
route.view 2nd params accepts only a string? or it also accept an imported component?

coz dynamic route import dont work with SSR... so there should be a way to pass a declared component , either thru 2nd params of route.view or on the options.

**Comment by md678685** [comment]
@codeitlikemiley 
> The resolver is actually optional... the default value is `resolver: (component) => component`.

If you don't call `setViewResolver`, it uses the view resolver that @raniesantos described above - meaning you can import components and use them when defining views. Correct me if I'm wrong, but as far as I can tell, this means your first suggested snippet should already work:
```javascript
//src/routes/home/index.js
import Route from 'vue-routisan'
import Home from '~/pages/index.vue'
Route.view('/', Home)
export default Route.all()
```

**Comment by raniesantos** [comment]
It accepts an imported component if you don't set a custom resolver.

**Comment by codeitlikemiley** [comment]
is Route.all() , an object or array... what does that return ?
can u give example output of that.

**Comment by raniesantos** [comment]
`.all()` returns an array. What the output looks like is basically what vue-router expects to be given, an array of route objects.

You can just `console.log` the return value of the method, but here's an example anyway.

![0341d3e0-5c58-475f-abab-bdc3ec03e204](https://user-images.githubusercontent.com/8528269/43915718-27eef94e-9c3e-11e8-8c35-6d5c84630bd1.png)

**Comment by codeitlikemiley** [comment]
thanks
@raniesantos  u have fb bro? add  me at fb username: uriah.san
